version: '3'

vars:
  VENV_PY: '{{if eq OS "windows"}}backend\\.venv\\Scripts\\python.exe{{else}}backend/.venv/bin/python{{end}}'

tasks:
  bootstrap:
    desc: Create venv and install CLI dependencies
    cmds:
      - python -m venv backend/.venv
      - '{{.VENV_PY}} -m pip install -U pip'
      - '{{.VENV_PY}} -m pip install -r backend/requirements.txt'
      - cmd: powershell -NoProfile -Command "if (-not (Test-Path 'config.yaml')) { Copy-Item 'config.example.yaml' 'config.yaml' }"
        platforms: [windows]
      - cmd: sh -c 'test -f config.yaml || cp config.example.yaml config.yaml'
        platforms: [linux, darwin]

  cli:help:
    desc: Show CLI help
    deps: [bootstrap]
    env:
      PYTHONPATH: backend
    cmds:
      - '{{.VENV_PY}} -m app.cli --help'

  cli:example:fetch:
    desc: Example register local GPKG (offline)
    deps: [bootstrap]
    env:
      PYTHONPATH: backend
    cmds:
      - '{{.VENV_PY}} -m app.cli fetch --bbox 12.5,55.6,12.6,55.7 --out cache --gpkg cache/DK_Building/building_inspire.gpkg'

  cli:example:generate:
    desc: Example generate (writes empty .map)
    deps: [bootstrap]
    env:
      PYTHONPATH: backend
    cmds:
      - '{{.VENV_PY}} -m app.cli generate --bbox 12.5,55.6,12.6,55.7 --out maps/example.map --wad halflife.wad'

  cli:fetch:skjern:
    desc: Fetch Skjern buildings (EPSG:4326) into cache/skjern
    deps: [bootstrap]
    env:
      PYTHONPATH: backend
    cmds:
      - '{{.VENV_PY}} -m app.cli fetch --bbox 8.491713,55.946504,8.495897,55.949315 --srs-name EPSG:4326 --out cache/skjern --gpkg cache/DK_Building/building_inspire.gpkg'

  cli:generate:
    desc: Generate Skjern .map from local GPKG
    deps: [bootstrap]
    env:
      PYTHONPATH: backend
    cmds:
      - '{{.VENV_PY}} -m app.cli generate --bbox 8.491713,55.946504,8.495897,55.949315 --gpkg cache/DK_Building/building_inspire.gpkg --out maps/skjern.map --wad halflife.wad --default-height 10 --scale 32'

  test:
    desc: Run pytest
    deps: [bootstrap]
    env:
      PYTHONPATH: backend
    cmds:
      - '{{.VENV_PY}} -m pytest -q'

